# Jupyter - Day 11 - Section 001
# Lec 11: More Logistic Regression

In this module we are going to test out the logistic regression classification method we discussed in class, but now we have:
- more than one input variable (multiple logistic regression) and,
- more than one level for the output variable (multinomial logistic regression).

In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd 
%matplotlib inline
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

Same as last time, we're going to use the `Default` data set from the ISLR book as included in their R package.  I've included a csv on the [DataSets page](../../DataSets/DataSets.md) for you to use.

In [4]:
url = "https://msu-cmse-courses.github.io/CMSE381-S26/_downloads/0bf0b0b65f603971cd33a04ad934449c/Default.csv"
Default = pd.read_csv(url)
Default.head(10)

  default student      balance        income
0      No      No   729.526495  44361.625070
1      No     Yes   817.180407  12106.134700
2      No      No  1073.549164  31767.138950
3      No      No   529.250605  35704.493940
4      No      No   785.655883  38463.495880
5      No     Yes   919.588531   7491.558572
6      No      No   825.513331  24905.226580
7      No     Yes   808.667504  17600.451340
8      No      No  1161.057854  37468.529290
9      No      No     0.000000  29275.268290

In [5]:
# Here's all the entries in the "default" column
list(Default['default'].unique())

['No', 'Yes']

## Multiple Logistic Regression 

We're going to be training models of the form 

$$
p(X) = \frac{\exp(\beta_0 + \beta_1 X_1 + \cdots + \beta_p X_p)}{1+\exp(\beta_0 + \beta_1 X_1 + \cdots + \beta_p X_p )}
$$


This time, we are going to use all three input variables to predict `default`. 
First things first, `student` is a categorical input variable. Let's deal with that. 

&#9989; **<font color=red>Do this:</font>** Add a dummy variable column called `student_Yes` to your data frame and remove the `student` column. Before moving on, make sure my check below prints out `True`.

In [6]:
Default['student_Yes'] = (Default['student'] == 'Yes').astype(int)
Default = Default.drop(columns=['student'])

In [8]:
# Check to see if you did that right!
# If your data frame is updated properly, this should print out True
list(Default.columns) == ['default', 'balance', 'income', 'student_Yes']

True

If you did all that right, the following should get us our train/test split of our inputs and outputs.

In [10]:
X = Default[['balance', 'income', 'student_Yes']]
y = Default['default']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

&#9989; **<font color=red>Do this:</font>** Set up a logistic regression model using inputs `balance`, `income`, and `student_Yes`. 
- Train this model on the training set above.

In [14]:
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

&#9989; **<font color=red>Do this:</font>** What is the equation of your model?

##YOUR ANSWER HERE### $p(default = 1 | X) = (e^{(-11.1082 + .005789 balance + .00000582 income - .4675 student_YES)})/(1 + e^{-11.1082 + .005789 balance + .00000582 income - .4675 student_{YES}})$

&#9989; **<font color=red>Do this:</font>** Use the test set to evaluate your model. What is the error?

In [15]:
# Your code here

y_pred = log_reg.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
error = 1 - accuracy
accuracy, error

(0.9733333333333334, 0.026666666666666616)

&#9989; **<font color=red>Do this:</font>** Take a look at the confusion matrix for this model. What do you notice?

In [17]:
# Your code here

conf_mat = confusion_matrix(y_test, y_pred)
conf_mat

# True Negatives (TN) = 2895 False Positives (FP) = 11
# False Negatives (FN) = 69 True Positives (TP) = 25
# The confusion matrix shows that the model predicts non-defaults
# very well but performs poorly at identifying actual defaults.
# Most errors are false negatives, indicating that despite high overall
# accuracy, the model struggles with the minority (default) class due to
# class imbalance.

array([[2895,   11],
       [  69,   25]])

## Multinomial Logistic Regression

Now we've got both multiple inputs and multiple levels. In this case we're going to use the `iris` data set but we're just going to use the version from `sklearn`. 

Take a moment to look at the [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html) or the [wikipedia page](https://en.wikipedia.org/wiki/Iris_flower_data_set) so you know what's going on in this data set.

In [18]:
from sklearn.datasets import load_iris

In [19]:

# just to remind me what the data is about.
iris_df = load_iris(as_frame=True)['frame']
print(iris_df.head())
print(load_iris()['target_names'])

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   target
0       0
1       0
2       0
3       0
4       0
['setosa' 'versicolor' 'virginica']

In [20]:
# I'm going to load in the data set and do a bit of processing so that it's in a nice format
iris_df = load_iris(as_frame=True)['frame']
target_names = load_iris()['target_names']
iris_df['species'] = target_names[load_iris()['target']]
iris_df.drop('target', axis=1, inplace=True)
iris_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

I've done all the hard work for you. The cell below does everything:
- Splits the data into X and y matrices. 
- Does a train/test split 
- Sets up the logistic regression classifier 
- Predicts the outputs for the test data 
- Reports an accuracy. 

*It might spit out a convergence warning for you, don't worry about it.*

In [22]:
X = iris_df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]
y = iris_df['species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=11)

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

Y_pred = logreg.predict(X_test)
err = 1-accuracy_score(y_test, Y_pred)
print(f'Error rate: {err*100:.2f}%')

Error rate: 13.33%

/opt/miniconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

&#9989; **<font color=red>Do this:</font>** 
- What do the columns of `predict_proba` function below correspond to? 
- Check your answer on the first few entries.

In [24]:
logreg.predict_proba(X_test)

array([[3.14455374e-05, 8.01467775e-02, 9.19821777e-01],
       [7.65073535e-05, 9.15529324e-02, 9.08370560e-01],
       [6.39425721e-04, 5.21850628e-01, 4.77509947e-01],
       [4.31411025e-03, 6.73554919e-01, 3.22130970e-01],
       [1.04910998e-04, 1.78747264e-01, 8.21147825e-01],
       [9.66310858e-01, 3.36890467e-02, 9.53678407e-08],
       [5.85476259e-03, 9.16466397e-01, 7.76788404e-02],
       [9.89302493e-01, 1.06974493e-02, 5.78375774e-08],
       [9.61582399e-01, 3.84173961e-02, 2.04902199e-07],
       [3.36629396e-03, 7.80837030e-01, 2.15796676e-01],
       [4.73657270e-04, 5.73809420e-01, 4.25716923e-01],
       [8.04824474e-03, 9.80487684e-01, 1.14640713e-02],
       [1.12036201e-02, 7.23184802e-01, 2.65611578e-01],
       [3.14484285e-04, 1.87978411e-01, 8.11707105e-01],
       [5.52889424e-05, 1.06531710e-01, 8.93413001e-01]])

In [26]:
##YOUR CODE HERE##

probs = logreg.predict_proba(X_test)
probs[:5]
logreg.predict(X_test)[:5]

array(['virginica', 'virginica', 'versicolor', 'versicolor', 'virginica'],
      dtype=object)

&#9989; **<font color=red>Q:</font>** 
Which of the classes is most often misclassified?

In [28]:
# Your code here

cm = confusion_matrix(y_test, Y_pred, labels=logreg.classes_)
cm_df = pd.DataFrame(cm, index=logreg.classes_, columns=logreg.classes_)
cm_df

# Virginica is the class that is most often misclassified.
# Even though versicolor is usually harder to classify in the full dataset,
# in this particular train/test split, the only errors occur when
# virginica is predicted as versicolor.

            setosa  versicolor  virginica
setosa           3           0          0
versicolor       0           5          0
virginica        0           2          5



-----
### Congratulations, we're done!
Initially created by Dr. Liz Munch, modified by Dr. Lianzhang Bao and Dr. Firas Khasawneh, Michigan State University

<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.